local root=app.params.root
assert(loadfile(root..'/extension/main.lua'))
local M=dofile(root..'/extension/codec.lua')
local ok,err=pcall(function()
  print('Aseprite '..tostring(app.version)..' API '..app.apiVersion)
  print('EMPTY JSON '..json.encode({runs={},palette={}}))
  for k,v in pairs(BlendMode) do print('BLEND '..k..' '..tostring(v)) end
  local decoded=json.decode('{"frames":[100],"width":8,"layers":[{"name":"Test","group":false}]}')
  for k,v in pairs(decoded.frames) do print('JSON array key '..tostring(k)..' '..type(k)..' '..tostring(v)) end
  local s=Sprite(8,8,ColorMode.RGB)
  s.layers[1].name='Unten'
  local im=Image(2,2,ColorMode.RGB)
  im:drawPixel(0,0,0x80443322); im:drawPixel(1,1,0xff998877)
  s:newCel(s.layers[1],1,im,Point(2,3))
  local group=s:newGroup(); group.name='Gruppe'
  local top=s:newLayer();top.parent=group;top.name='Oben';top.opacity=180
  s:newEmptyFrame(2);s.frames[2].duration=0.25
  s:newCel(top,2,im,Point(0,0))
  local snapshot=M.capture(s)
  assert(#snapshot.layers==3 and snapshot.layers[3].parent==2)
  local copy,map=M.create(snapshot)
  local other=M.capture(copy)
  assert(json.encode(snapshot.layers)==json.encode(other.layers),'Layer mismatch')
  assert(json.encode(snapshot.cels)==json.encode(other.cels),'Cel mismatch')
  assert(other.frames[2]==250)
  local pixels=M.decode(other)
  assert(string.unpack('<I4',pixels['1:1'].bytes,(3*8+2)*4+1)==0x80443322)
  M.checkTopology(copy,map,snapshot)
  local base=string.rep('\0',16)
  local changed=M.applyRuns(base,{0,1,0xff112233,3,1,0x99aabbcc})
  local runs=M.runs(changed,base)
  assert(#runs==6 and runs[1]==0 and runs[2]==1 and runs[3]==0xff112233 and runs[4]==3 and runs[6]==0x99aabbcc)
  assert(M.applyRuns(changed,{0,4,0})==base)
  local scan=M.scan(copy,map)
  local cached=M.scan(copy,map,scan)
  assert(scan['1:1']==cached['1:1'])
  local moved=Sprite(4,4,ColorMode.RGB)
  local movedImage=Image(2,2,ColorMode.RGB)
  movedImage:drawPixel(1,0,0xff123456)
  moved:newCel(moved.layers[1],1,movedImage,Point(-1,0))
  local movedScan=M.scan(moved,{moved.layers[1]})
  assert(string.unpack('<I4',movedScan['1:1'].bytes,1)==0xff123456,'Off-canvas crop failed')
  moved:close()
  print('PASS: RGBA, alpha, offset/off-canvas cels, groups, frames, palette, RLE, cache')
  copy:close();s:close()
end)
local f=assert(io.open(root..'/test-results/codec-result.txt','w'))
f:write(ok and 'PASS' or tostring(err)); f:close()
if not ok then error(err) end
