local C=dofile(app.params.root..'/extension/codec.lua')
local source=assert(app.open(app.params.input))
local snapshot=C.capture(source)
local copied,mapping=C.create(snapshot)
local result=C.capture(copied)
assert(json.encode(snapshot.layers)==json.encode(result.layers),'Ebenen veraendert')
assert(json.encode(snapshot.cels)==json.encode(result.cels),'Pixel/Cels veraendert')
assert(json.encode(snapshot.frames)==json.encode(result.frames),'Frames veraendert')
assert(json.encode(snapshot.palette)==json.encode(result.palette),'Palette veraendert')
print('PASS existing artwork: '..snapshot.width..'x'..snapshot.height..', '..#snapshot.layers..' layers, '..#snapshot.frames..' frames; original not saved/modified')
copied:close();source:close()
