"""Generate a compact, one-bit OFL title font for Aseprite's idea board."""
from pathlib import Path
from PIL import Image, ImageDraw, ImageFont

root = Path(__file__).resolve().parents[1]
font = ImageFont.truetype(root / "tools/fonts/AtkinsonHyperlegible-Bold.ttf", 19)
characters = list(range(32, 127)) + list(range(160, 384))
characters += [0x2022, 0x2026, 0x2013, 0x2014, 0x20AC, 0x2192]
height = 26
lines = ["-- Generated by tools/build-heading-font.py; Atkinson Hyperlegible, OFL 1.1.",
         f"return {{height={height},glyphs={{"]
for codepoint in characters:
    advance = round(font.getlength(chr(codepoint)))
    width = max(advance + 4, 8)
    image = Image.new("L", (width, height))
    ImageDraw.Draw(image).text((2, 0), chr(codepoint), font=font, fill=255)
    rows = []
    for y in range(height):
        bits = 0
        for x in range(width):
            if image.getpixel((x, y)) >= 112:
                bits |= 1 << x
        rows.append(f"{bits:x}")
    lines.append(f"[{codepoint}]={{{advance},{width},{{{','.join(repr(row) for row in rows)}}}}},")
lines.append("}}")
(root / "extension/notes-heading-data.lua").write_text("\n".join(lines) + "\n", encoding="utf-8")
