name: Tests

on:
  push:
  pull_request:

jobs:
  node-tests:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '24'
          cache: npm
      - run: npm ci
      - run: npm test
      - shell: pwsh
        run: ./test/update.ps1
      - shell: pwsh
        run: ./build.ps1
      - shell: pwsh
        run: ./test/bootstrap.ps1
